---

- name: 'Install required repository configs'
  package:
    name: '{{ item }}'
    state: 'latest'
  with_items:
    - 'epel-release'
    - 'centos-release-yum4'
    - 'centos-release-qemu-ev'

- name: 'Install common packages'
  package:
    name: '{{ item }}'
    state: 'latest'
  with_items:
    - 'mosh'
    - 'vim-enhanced'
    - 'rkhunter'

- name: 'Install tuned'
  package:
    name: 'tuned'
    state: 'latest'

- name: 'Enable tuned'
  service:
    name: 'tuned'
    enabled: true
    state: 'started'

- name: 'Set tuned profile to {{ tuned_profile }}'
  shell: 'tuned-adm profile {{ tuned_profile }}'
